### ISSUE TITLE
Add gzip compression

### ISSUE THREAD

**Issue by aapris** [City-of-Helsinki/lidotiku#61]
If you add above this line
https://github.com/City-of-Helsinki/lidotiku/blob/5f38c72df6ceb66534cc3b13a8a83291d2edddf7/lidotiku/settings.py#L59
a new middleware:
`    "django.middleware.gzip.GZipMiddleware",`
the content-length of responses will shrink 95-98% (at least when using `format=csv`).

For example this request
`https://lidotiku.api.dev.hel.ninja/api/observations/?counter=100016108&page_size=10000&format=csv&start_date=2023-06-01&end_date=2023-09-01`
creates a response having
`Content-Length: 1231978`
but when the payload is compressed, it will be only `38442` bytes (3.1% of the uncompressed payload).

I can fork this repo and make a pull request if you wish, or you can add that line by yourself and close this issue then?

**Comment by ndinatale-nc** [comment]
Added the middleware, thanks for the suggestion
